name: DNNE

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [master]
    paths-ignore:
      - '**/*.md'

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [ 'Debug', 'Release' ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true
    - name: Build Product and Package
      run: dotnet build src/create_package.proj -c ${{ matrix.flavor }}
    - name: Unit Test Product
      run: dotnet test test/DNNE.UnitTests -c ${{ matrix.flavor }}
    - name: Unit Test Product (gcc)
      run: |
        dotnet clean test/DNNE.UnitTests -c ${{ matrix.flavor }}
        dotnet test test/DNNE.UnitTests -c ${{ matrix.flavor }} -p:BuildWithGCC=true
    - name: Unit Test Product (g++)
      run: |
        dotnet clean test/DNNE.UnitTests -c ${{ matrix.flavor }}
        dotnet test test/DNNE.UnitTests -c ${{ matrix.flavor }} -p:BuildWithGPP=true
    - name: Upload Package
      uses: actions/upload-artifact@v2
      with:
        name: package.${{ matrix.flavor }}
        path: src/dnne-pkg/bin/${{ matrix.flavor }}/DNNE.*.nupkg

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        flavor: [ 'Debug', 'Release' ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true
    - name: Build Product and Package
      run: dotnet build src\create_package.proj -c ${{ matrix.flavor }}
    - name: Build ExportingAssembly (.NET Core and .NET Framework)
      run: dotnet build test\ExportingAssembly -c ${{ matrix.flavor }}
    - name: Unit Test Product (cpp)
      run: |
        dotnet clean test\DNNE.UnitTests -c ${{ matrix.flavor }}
        dotnet test test\DNNE.UnitTests -c ${{ matrix.flavor }} -p:BuildAsCPPWithMSVC=true
    - name: Unit Test Product
      run: |
        dotnet clean test\DNNE.UnitTests -c ${{ matrix.flavor }}
        dotnet test test\DNNE.UnitTests -c ${{ matrix.flavor }}

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        flavor: [ 'Debug', 'Release' ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true
    - name: Build Product and Package
      run: dotnet build src/create_package.proj -c  ${{ matrix.flavor }}
    - name: Unit Test Product
      run: dotnet test test/DNNE.UnitTests -c  ${{ matrix.flavor }}
    - name: Unit Test Product (clang++)
      run: |
        dotnet clean test/DNNE.UnitTests -c ${{ matrix.flavor }}
        dotnet test test/DNNE.UnitTests -c  ${{ matrix.flavor }} -p:BuildWithClangPP=true
